### PR TITLE
fix import path to be relative; closes #45

### LINKED ISSUE #45: BUG: application middleware cannot find package.json
```typescript
import packageJson from 'package.json';
```

Though this would work, but should be relative (or add an alias for project root

### PR DESCRIPTION
**Pull request by p-mcgowan**

### CODE REVIEW

File: src/http/nodegen/middleware/applicationMiddleware.ts [hunk 1]
```diff
@@ -13,8 +13,8 @@ import express from 'express';
 import expressFormData from 'express-form-data';
 import morgan from 'morgan';
 import { tmpdir } from 'os';
-import packageJson from 'package.json';
 import requestIp from 'request-ip';
+import packageJson from '../../../../package.json';
```
Comment (jeicken) [inline src/http/nodegen/middleware/applicationMiddleware.ts:17]: Shouldn't this be possible with '@/package.json' as well?

**Review by jeicken — COMMENTED** [review]
Really REALLY do not like how node handles paths...

File: src/http/nodegen/middleware/applicationMiddleware.ts (hunk 1 above)
Comment (p-mcgowan) [reply src/http/nodegen/middleware/applicationMiddleware.ts:17]: I would love to add a root alias - I think that's a great idea.

specifically `@/package` would currently reference the src folder, but we can add `@root/` or something like that, as `@/<rootfile>` might be confusing

Comment (Acrontum-Carmichael) [reply src/http/nodegen/middleware/applicationMiddleware.ts:17]: never seen this in a ts project before - lets leave it off for now and Jan could you try this in 1 of your projects and see how it goes? btw: this is how most languages work, a configurable setting to define where imports can come from..

**Review by Acrontum-Carmichael — APPROVED** [review]

**Comment by Acrontum-Carmichael** [comment]
this should be going into develop not master

File: src/http/nodegen/middleware/applicationMiddleware.ts (hunk 1 above)
Comment (Acrontum-Carmichael) [reply src/http/nodegen/middleware/applicationMiddleware.ts]: @p-mcgowan have you worked with an API where there is a root path shortcut?

Comment (jeicken) [reply src/http/nodegen/middleware/applicationMiddleware.ts]: sure can, in a composer.json you can define exactly those autoloads with PSR-4 ;)
Sure thing will try it out somewhere first and create a MR then

Comment (p-mcgowan) [reply src/http/nodegen/middleware/applicationMiddleware.ts]: Nope, have not used root alias, but it could have been useful a few times - for example when sequelize config and migrations live outside the src folder, or if a frontend is importing backend typings from a shared root.

I'm easy either way - I really like that the aliases allow for moving files around very easily, but it it's just for this one file then  although it's a bit uggo I don't see a problem with leaving the relative path in - I think it's relatively uncommon to import package.json - in fact I believe there will be env vars set containing the package.name already

**Comment by p-mcgowan** [comment]
reverting the root alias - this could be something we make an issue for an talk about if / why we want it.

since the rest of this just un-breaks the app, and up to that commit was already approved, I'm going to go ahead and merge so I can get back to work
